### ISSUE TITLE
Current Solution Code is not passing all TCs

### ISSUE THREAD

**Issue by byojelly** [learn-co-curriculum/js-dom-and-events-konami-code-lab#2]
with the following solution code in konami_code.js, running tests and mocha.run() in console still generates failed tests.

```
const code = [38, 38, 40, 40, 37, 39, 37, 39, 66, 65];

function init() {
  let index = 0;

  document.body.addEventListener('keydown', function(e) {
    const key = parseInt(e.which || e.detail);
    if (code[index] === key) {
      index++;
      if (index === (code.length)) {
              alert("Hurray!");
              index = 0;
      }
    } else {
      index = 0;
    }
  });
}
```

![image](https://user-images.githubusercontent.com/17861241/41449008-63f70d52-702c-11e8-86a2-921f6d345a04.png)

**Comment by maxwellbenton** [comment]
Hi there @byojelly,

I'm having difficulty reproducing the issue, so I'm going to close it for now. However, we have updated this lesson's package.json file and confirmed that using the code you provided will successfully pass the tests in this lesson.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
