### ISSUE TITLE
FYI -- Receiving Mocha error

### ISSUE THREAD

**Issue by raiet13** [learn-co-curriculum/js-dom-and-events-konami-code-lab#5]
Cloned a fresh copy of this lab and encountered the issue below when attempting to run "learn test".

 1)  "before all" hook:
     Error: Cannot find module 'jsdom/lib/old-api'
      at require (internal/module.js:20:19)
      at Context.<anonymous> (node_modules/mocha-jsdom/index.js:53:5)

Just an FYI. Suggest updating or adding some sort of notification that links to resources for the issue (since it is apparently affecting multiple labs).
// https://github.com/learn-co-curriculum/js-what-is-a-test-lab/issues/11
// https://github.com/learn-co-curriculum/moving-things-with-javascript/issues/17

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @raiet13 .

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
