### ISSUE TITLE
mocha.run() does not work

### ISSUE THREAD

**Issue by coryjbergquist** [learn-co-curriculum/js-dom-and-events-konami-code-lab#6]
index.html says to use "mocha.run()" to run tests in the browser. Tests pass when using "learn" in console, and entering the Konami code in the browser gives the correct alert, but mocha.run() gives this error:
 `Error: spy was not called
    at a (node_modules/expect/umd/expect.min.js:1:1122)
    at t.value (node_modules/expect/umd/expect.min.js:1:8394)
    at Context.it (test/index-test.js:32:28)`

**Comment by maxwellbenton** [comment]
Hi @coryjbergquist  ,

I'm having difficulty reproducing the issue, but have updated `index.html` and the solution branch to make sure it is working without error.

I'm going to close this issue for now, but if you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
